2016-06-10 02:19:49,535 : INFO : Machine : Mission Pinball Framework Core Engine v0.30.0.dev1705
2016-06-10 02:19:49,535 : INFO : Machine : Machine path: /Users/gabe/Dropbox/Pinball/Gabe/bnd
2016-06-10 02:19:49,762 : INFO : Machine : Loading config from original files
2016-06-10 02:19:49,807 : INFO : Machine : Machine config file #1: /Users/gabe/Dropbox/Pinball/Gabe/bnd/config/config
2016-06-10 02:19:49,945 : INFO : Machine : Config file cache created: /var/folders/c1/z5pg47y54_s14cd2m1zmk1kc0000gn/T/db0cb78b77a969ed262a283d7c7743faconfig
2016-06-10 02:19:49,945 : INFO : Machine : Starting clock at 30.0Hz
2016-06-10 02:19:49,966 : INFO : FAST : Connecting to /dev/tty.usbserial-142C at 921600bps
2016-06-10 02:19:51,483 : INFO : FAST : Connecting to /dev/tty.usbserial-142B at 921600bps
2016-06-10 02:19:53,066 : INFO : Machine : Shutting down...
2016-06-10 02:19:53,117 : ERROR : root : invalid literal for int() with base 10: '0B'
Traceback (most recent call last):
  File "/Applications/MPF.app/Contents/Frameworks/python/3.5.0/lib/python3.5/site-packages/mpf/commands/game.py", line 130, in __init__
    MachineController(mpf_path, machine_path, vars(args)).run()
  File "/Applications/MPF.app/Contents/Frameworks/python/3.5.0/lib/python3.5/site-packages/mpf/core/machine.py", line 127, in __init__
    self._run_init_phases()
  File "/Applications/MPF.app/Contents/Frameworks/python/3.5.0/lib/python3.5/site-packages/mpf/core/machine.py", line 144, in _run_init_phases
    self.events.process_event_queue()
  File "/Applications/MPF.app/Contents/Frameworks/python/3.5.0/lib/python3.5/site-packages/mpf/core/events.py", line 481, in process_event_queue
    **event[3])
  File "/Applications/MPF.app/Contents/Frameworks/python/3.5.0/lib/python3.5/site-packages/mpf/core/events.py", line 416, in _process_event
    result = handler[0](**merged_kwargs)
  File "/Applications/MPF.app/Contents/Frameworks/python/3.5.0/lib/python3.5/site-packages/mpf/core/device_manager.py", line 60, in _load_device_modules
    self.initialize_devices()
  File "/Applications/MPF.app/Contents/Frameworks/python/3.5.0/lib/python3.5/site-packages/mpf/core/device_manager.py", line 139, in initialize_devices
    collection[device_name].device_added_system_wide()
  File "/Applications/MPF.app/Contents/Frameworks/python/3.5.0/lib/python3.5/site-packages/mpf/core/system_wide_device.py", line 7, in device_added_system_wide
    self._initialize()
  File "/Applications/MPF.app/Contents/Frameworks/python/3.5.0/lib/python3.5/site-packages/mpf/devices/servo.py", line 28, in _initialize
    self.hw_servo = self.platform.configure_servo(self.config)
  File "/Applications/MPF.app/Contents/Frameworks/python/3.5.0/lib/python3.5/site-packages/mpf/platforms/fast/fast.py", line 326, in configure_servo
    number = self._convert_number_from_config(config['number'])
  File "/Applications/MPF.app/Contents/Frameworks/python/3.5.0/lib/python3.5/site-packages/mpf/platforms/fast/fast.py", line 280, in _convert_number_from_config
    return Util.int_to_hex_string(number)
  File "/Applications/MPF.app/Contents/Frameworks/python/3.5.0/lib/python3.5/site-packages/mpf/core/utility_functions.py", line 249, in int_to_hex_string
    source_int = int(source_int)
ValueError: invalid literal for int() with base 10: '0B'
