2016-05-13 23:30:39,723 : INFO : Machine : Mission Pinball Framework Core Engine v0.30.0.dev1482
2016-05-13 23:30:39,723 : INFO : Machine : Machine path: /Users/gabe/Dropbox/Pinball/Gabe/bnd
2016-05-13 23:30:39,938 : INFO : Machine : Loading config from original files
2016-05-13 23:30:39,989 : INFO : Machine : Machine config file #1: /Users/gabe/Dropbox/Pinball/Gabe/bnd/config/config
2016-05-13 23:30:40,128 : INFO : Machine : Config file cache created: /var/folders/c1/z5pg47y54_s14cd2m1zmk1kc0000gn/T/db0cb78b77a969ed262a283d7c7743faconfig
2016-05-13 23:30:40,128 : INFO : Machine : Starting clock at 30.0Hz
2016-05-13 23:30:40,142 : INFO : FAST : Configuring FAST hardware.
2016-05-13 23:30:40,142 : INFO : Machine : Loading core modules...
2016-05-13 23:30:40,153 : INFO : FAST : Configuring FAST Controller for FAST IO boards.
2016-05-13 23:30:40,153 : INFO : FAST : Connecting to /dev/tty.usbserial-141C at 921600bps
2016-05-13 23:30:41,670 : INFO : FAST : Received ID acknowledgement. Processor: RGB, Board: FP-CPU-002-2, Firmware: 01.00
2016-05-13 23:30:41,671 : INFO : FAST : Connecting to /dev/tty.usbserial-141B at 921600bps
2016-05-13 23:30:43,189 : INFO : FAST : Received ID acknowledgement. Processor: NET, Board: FP-CPU-002-2, Firmware: 01.00
2016-05-13 23:30:43,206 : INFO : FAST : Fast IO Board 00: Model: FP-I/O-3208-2, Firmware: 01.00, Switches: 32, Drivers: 8
2016-05-13 23:30:43,221 : INFO : FAST : Fast IO Board 01: Model: FP-I/O-3208-2, Firmware: 01.00, Switches: 32, Drivers: 8
2016-05-13 23:30:43,223 : INFO : FAST : Fast IO Board 02: Model: FP-I/O-1616-2, Firmware: 01.00, Switches: 16, Drivers: 16
2016-05-13 23:30:43,258 : ERROR : ConfigProcessor : Your config contains a value for the setting "hardware:pololu_maestro", but this is not a valid setting name.
2016-05-13 23:30:43,258 : ERROR : root : Your config contains a value for the setting "hardware:pololu_maestro", but this is not a valid setting name.
Traceback (most recent call last):
  File "/Applications/MPF.app/Contents/Frameworks/python/3.5.0/lib/python3.5/site-packages/mpf/commands/game.py", line 130, in __init__
    MachineController(mpf_path, machine_path, vars(args)).run()
  File "/Applications/MPF.app/Contents/Frameworks/python/3.5.0/lib/python3.5/site-packages/mpf/core/machine.py", line 122, in __init__
    self._validate_config()
  File "/Applications/MPF.app/Contents/Frameworks/python/3.5.0/lib/python3.5/site-packages/mpf/core/machine.py", line 192, in _validate_config
    self.validate_machine_config_section('hardware')
  File "/Applications/MPF.app/Contents/Frameworks/python/3.5.0/lib/python3.5/site-packages/mpf/core/machine.py", line 203, in validate_machine_config_section
    section, self.config[section], section)
  File "/Applications/MPF.app/Contents/Frameworks/python/3.5.0/lib/python3.5/site-packages/mpf/core/config_validator.py", line 1225, in validate_config
    validation_failure_info)
  File "/Applications/MPF.app/Contents/Frameworks/python/3.5.0/lib/python3.5/site-packages/mpf/core/config_validator.py", line 1358, in check_for_invalid_sections
    'setting "' + path_string + '", but this is not a valid '
AssertionError: Your config contains a value for the setting "hardware:pololu_maestro", but this is not a valid setting name.
