2016-05-27 23:57:42,392 : INFO : Machine : Mission Pinball Framework Core Engine v0.30.0.dev1633
2016-05-27 23:57:42,392 : INFO : Machine : Machine path: /Users/gabe/Dropbox/Pinball/Gabe/bnd
2016-05-27 23:57:42,574 : INFO : Machine : Loading cached config: /var/folders/c1/z5pg47y54_s14cd2m1zmk1kc0000gn/T/db0cb78b77a969ed262a283d7c7743faconfig
2016-05-27 23:57:42,574 : INFO : Machine : Starting clock at 30.0Hz
2016-05-27 23:57:42,593 : INFO : FAST : Connecting to /dev/tty.usbserial-142C at 921600bps
2016-05-27 23:57:44,111 : INFO : FAST : Connecting to /dev/tty.usbserial-142B at 921600bps
2016-05-27 23:57:45,694 : ERROR : ConfigProcessor : Your config contains a value for the setting "hardware:pololu_maestro", but this is not a valid setting name.
2016-05-27 23:57:45,694 : ERROR : root : Your config contains a value for the setting "hardware:pololu_maestro", but this is not a valid setting name.
Traceback (most recent call last):
  File "/Applications/MPF.app/Contents/Frameworks/python/3.5.0/lib/python3.5/site-packages/mpf/commands/game.py", line 130, in __init__
    MachineController(mpf_path, machine_path, vars(args)).run()
  File "/Applications/MPF.app/Contents/Frameworks/python/3.5.0/lib/python3.5/site-packages/mpf/core/machine.py", line 118, in __init__
    self._validate_config()
  File "/Applications/MPF.app/Contents/Frameworks/python/3.5.0/lib/python3.5/site-packages/mpf/core/machine.py", line 184, in _validate_config
    self.validate_machine_config_section('hardware')
  File "/Applications/MPF.app/Contents/Frameworks/python/3.5.0/lib/python3.5/site-packages/mpf/core/machine.py", line 195, in validate_machine_config_section
    section, self.config[section], section)
  File "/Applications/MPF.app/Contents/Frameworks/python/3.5.0/lib/python3.5/site-packages/mpf/core/config_validator.py", line 1229, in validate_config
    validation_failure_info)
  File "/Applications/MPF.app/Contents/Frameworks/python/3.5.0/lib/python3.5/site-packages/mpf/core/config_validator.py", line 1362, in check_for_invalid_sections
    'setting "' + path_string + '", but this is not a valid '
AssertionError: Your config contains a value for the setting "hardware:pololu_maestro", but this is not a valid setting name.
