2016-03-11 14:59:16,528 : INFO : Machine : Mission Pinball Framework v0.30.0.dev615
2016-03-11 14:59:16,529 : INFO : Machine : Loading cached config: /Users/gabe/pinball/bnd/__mpfcache__/config_config.p
2016-03-11 14:59:16,538 : INFO : FAST : Configuring FAST hardware.
2016-03-11 14:59:16,538 : INFO : Machine : Loading core modules...
2016-03-11 14:59:16,699 : INFO : FAST : Configuring FAST Controller for FAST IO boards.
2016-03-11 14:59:16,699 : INFO : FAST : Connecting to /dev/tty.usbserial-141C at 921600bps
2016-03-11 14:59:18,202 : ERROR : root : unicode strings are not supported, please encode to bytes: 'ID:\r'
Traceback (most recent call last):
  File "/Users/gabe/pinball/mpf30/mpf/commands/core.py", line 135, in __init__
    MachineController(mpf_path, machine_path, vars(args)).run()
  File "/Users/gabe/pinball/mpf30/mpf/core/machine.py", line 120, in __init__
    platform.initialize()
  File "/Users/gabe/pinball/mpf30/mpf/platforms/fast.py", line 284, in initialize
    self._connect_to_hardware()
  File "/Users/gabe/pinball/mpf30/mpf/platforms/fast.py", line 318, in _connect_to_hardware
    send_queue=queue.Queue(), receive_queue=self.receive_queue))
  File "/Users/gabe/pinball/mpf30/mpf/platforms/fast.py", line 1250, in __init__
    self.identify_connection()
  File "/Users/gabe/pinball/mpf30/mpf/platforms/fast.py", line 1264, in identify_connection
    self.serial_connection.write('ID:\r')
  File "/Applications/Kivy.app/Contents/Frameworks/python/3.5.0/lib/python3.5/site-packages/serial/serialposix.py", line 518, in write
    d = to_bytes(data)
  File "/Applications/Kivy.app/Contents/Frameworks/python/3.5.0/lib/python3.5/site-packages/serial/serialutil.py", line 58, in to_bytes
    raise TypeError('unicode strings are not supported, please encode to bytes: %r' % (seq,))
TypeError: unicode strings are not supported, please encode to bytes: 'ID:\r'
